In [29]:
%load_ext autoreload
%autoreload 2

import numpy as np
import matplotlib.pyplot as plt
import scipy.sparse as sp  

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [78]:
p=5
tet="tet3"
mur=32
alpha=0.01
vol=0.9427794561617878

if tet=="tet0":
    directory="Results/CSG_Tetra_0/al_0.01_mu_32_sig_1e7/1e-3-1e12_3000_el_21155_ord_"+str(p)+"_POD_50_1e-6"
    ck=np.genfromtxt(directory+'/Data/Amplitudes.csv', delimiter=',')
    xi=np.genfromtxt(directory+'/Data/Modes.csv', delimiter=',')
    Omega=np.genfromtxt(directory+'/Data/Frequencies.csv', delimiter=',')
    time=np.genfromtxt(directory+'/Data/Time.csv', delimiter=',')
    Sgn_step= np.genfromtxt(directory+'/Data/Sgn_step.csv', delimiter=',')
    Sgn_impulse= np.genfromtxt(directory+'/Data/Sgn_impulse.csv', delimiter=',')
    TensorArray= np.genfromtxt(directory+'/Data/Tensors.csv', delimiter=',', dtype=complex)
    Eigenvalues=np.genfromtxt(directory+'/Data/Eigenvalues.csv', delimiter=',', dtype=complex)
    Minf= np.genfromtxt(directory+'/Data/Minf.csv', delimiter=',')
    N0= np.genfromtxt(directory+'/Data/N0.csv', delimiter=',')    
elif tet=="tet1":
    directory="Results/CSG_Tetra_1/al_0.01_mu_32_sig_1e7/1e-3-1e12_3000_el_21211_ord_"+str(p)+"_POD_50_1e-6"
    ck=np.genfromtxt(directory+'/Data/Amplitudes.csv', delimiter=',')
    xi=np.genfromtxt(directory+'/Data/Modes.csv', delimiter=',')
    Omega=np.genfromtxt(directory+'/Data/Frequencies.csv', delimiter=',')
    time=np.genfromtxt(directory+'/Data/Time.csv', delimiter=',')
    Sgn_step= np.genfromtxt(directory+'/Data/Sgn_step.csv', delimiter=',')
    Sgn_impulse= np.genfromtxt(directory+'/Data/Sgn_impulse.csv', delimiter=',')
    TensorArray= np.genfromtxt(directory+'/Data/Tensors.csv', delimiter=',', dtype=complex)
    Eigenvalues=np.genfromtxt(directory+'/Data/Eigenvalues.csv', delimiter=',', dtype=complex)
    Minf= np.genfromtxt(directory+'/Data/Minf.csv', delimiter=',')
    N0= np.genfromtxt(directory+'/Data/N0.csv', delimiter=',') 
elif tet=="tet2":
    directory="Results/CSG_Tetra_2/al_0.01_mu_32_sig_1e7/1e-3-1e12_3000_el_21771_ord_"+str(p)+"_POD_50_1e-6"
    ck=np.genfromtxt(directory+'/Data/Amplitudes.csv', delimiter=',')
    xi=np.genfromtxt(directory+'/Data/Modes.csv', delimiter=',')
    Omega=np.genfromtxt(directory+'/Data/Frequencies.csv', delimiter=',')
    time=np.genfromtxt(directory+'/Data/Time.csv', delimiter=',')
    Sgn_step= np.genfromtxt(directory+'/Data/Sgn_step.csv', delimiter=',')
    Sgn_impulse= np.genfromtxt(directory+'/Data/Sgn_impulse.csv', delimiter=',')
    TensorArray= np.genfromtxt(directory+'/Data/Tensors.csv', delimiter=',', dtype=complex)
    Eigenvalues=np.genfromtxt(directory+'/Data/Eigenvalues.csv', delimiter=',', dtype=complex)
    Minf= np.genfromtxt(directory+'/Data/Minf.csv', delimiter=',')
    N0= np.genfromtxt(directory+'/Data/N0.csv', delimiter=',')  
elif tet=="tet3":
    directory="Results/CSG_Tetra_3/al_0.01_mu_32_sig_1e7/1e-3-1e12_3000_el_22401_ord_"+str(p)+"_POD_50_1e-6"
    ck=np.genfromtxt(directory+'/Data/Amplitudes.csv', delimiter=',')
    xi=np.genfromtxt(directory+'/Data/Modes.csv', delimiter=',')
    Omega=np.genfromtxt(directory+'/Data/Frequencies.csv', delimiter=',')
    time=np.genfromtxt(directory+'/Data/Time.csv', delimiter=',')
    Sgn_step= np.genfromtxt(directory+'/Data/Sgn_step.csv', delimiter=',')
    Sgn_impulse= np.genfromtxt(directory+'/Data/Sgn_impulse.csv', delimiter=',')
    TensorArray= np.genfromtxt(directory+'/Data/Tensors.csv', delimiter=',', dtype=complex)
    Eigenvalues=np.genfromtxt(directory+'/Data/Eigenvalues.csv', delimiter=',', dtype=complex)
    Minf= np.genfromtxt(directory+'/Data/Minf.csv', delimiter=',')
    N0= np.genfromtxt(directory+'/Data/N0.csv', delimiter=',')      
elif tet=="tet4":
    directory="Results/CSG_Tetra_4/al_0.01_mu_32_sig_1e7/1e-3-1e12_3000_el_24051_ord_"+str(p)+"_POD_50_1e-6"
    ck=np.genfromtxt(directory+'/Data/Amplitudes.csv', delimiter=',')
    xi=np.genfromtxt(directory+'/Data/Modes.csv', delimiter=',')
    Omega=np.genfromtxt(directory+'/Data/Frequencies.csv', delimiter=',')
    time=np.genfromtxt(directory+'/Data/Time.csv', delimiter=',')
    Sgn_step= np.genfromtxt(directory+'/Data/Sgn_step.csv', delimiter=',')
    Sgn_impulse= np.genfromtxt(directory+'/Data/Sgn_impulse.csv', delimiter=',')
    TensorArray= np.genfromtxt(directory+'/Data/Tensors.csv', delimiter=',', dtype=complex)
    Eigenvalues=np.genfromtxt(directory+'/Data/Eigenvalues.csv', delimiter=',', dtype=complex)
    Minf= np.genfromtxt(directory+'/Data/Minf.csv', delimiter=',')
    N0= np.genfromtxt(directory+'/Data/N0.csv', delimiter=',')    

In [79]:
# Ellipsoid for N0

In [80]:
from equiv_ellip import *
EvN0,QN0=np.linalg.eig(N0)      
order=np.argsort(-EvN0)
print(order)
EvN0=EvN0[order]
LamPS=np.zeros((3,3),dtype=float)
for i in range(3):
    LamPS[i,i]=EvN0[i]
print(LamPS)

[0 2 1]
[[8.61732200e-06 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 4.25500456e-06 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.04547162e-06]]


In [82]:
vol_ellip=(1+3/(mur-1))/(alpha**3*np.trace(np.linalg.inv(LamPS)))
print(vol,vol_ellip)
Hill=np.linalg.inv(LamPS)*alpha**3*vol_ellip-np.eye(3)/(mur-1)
print("Hill Tensor")
print(Hill)
if np.abs(np.trace(Hill)-1.) > 1e-12:
    print("Trace of Hill tensor is not 1",np.trace(Hill))
    old_trace=np.trace(Hill)
    Hill=Hill/old_trace
    print(Hill)

tol=None
ellip=find_ellipsoid(Hill,vol_ellip,tol)
print("Computed vol",4/3*np.pi*ellip[0]*ellip[1]*ellip[2])
PS,Hill=PStensor(ellip[0],ellip[1],ellip[2],alpha,mur,vol_ellip)
print("Tolerance=",tol,"Error in PS",np.linalg.norm(PS-LamPS)/np.linalg.norm(LamPS))

0.9427794561617878 1.3057651518851312
Hill Tensor
[[0.11926989 0.         0.        ]
 [0.         0.27461943 0.        ]
 [0.         0.         0.60611068]]
solution to min problem [0.25918867 0.53692299]
Ellipsoid found is  [1.30842697 0.70252452 0.33912944]
Computed vol 1.3057651518851314
0.11926988566522223
PS Tensor
[[8.61732209e-06 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 4.25500463e-06 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.04547160e-06]]
Hill Tensor
[[0.11926989 0.         0.        ]
 [0.         0.27461943 0.        ]
 [0.         0.         0.60611069]]
Tolerance= None Error in PS 1.1231314831422955e-08


In [83]:
# ellipsoid for Minf

In [84]:
EvMinf,QMinf=np.linalg.eig(Minf)      
order=np.argsort(-EvMinf)
EvMinf=EvMinf[order]
print(EvMinf)
LamPS=np.zeros((3,3),dtype=float)
LamPSs=np.zeros((3,3),dtype=float)

for i in range(3):
    LamPS[i,i]=EvMinf[i]
    LamPSs[i,i]=EvMinf[i]/alpha**3

print(LamPS)
# Find equivalent ellipsoid for infinite case
alphan=alpha
#vol_ellip=-2./(alphan**3*np.trace(np.linalg.inv(LamPS)))
vol_ellip=-2./(( 1/LamPSs[0,0]+ 1/LamPSs[1,1]+ 1/LamPSs[2,2] ))

print("elliptic volume,",vol_ellip)
Hill= np.zeros((3,3))
for i in range(3):
    Hill[i,i]=vol_ellip/LamPSs[i,i]+1
print(Hill)
#if Hill[0,0]<0:
#    # fix smallest value
#    error=1e-5-Hill[0,0]
#    Hill[0,0]=1e-5
#    Hill[1,1]=Hill[1,1]-error/2
#    Hill[2,2]=Hill[2,2]-error/2
#    #vol_ellip=(np.linalg.trace(Hill)-3)*(1/LamPSs[0,0]+ 1/LamPSs[1,1]+ 1/LamPSs[2,2] )
#    print("elliptic volume,",vol_ellip)
print("Hill Tensor")
print(Hill)
if np.abs(np.trace(Hill)-1.) > 1e-12:
    print("Trace of Hill tensor is not 1",np.trace(Hill))
    old_trace=np.trace(Hill)
    Hill=Hill/old_trace
    print(Hill)
tol=None
ellipinf=find_ellipsoid(Hill,vol_ellip,tol=tol)
PS,Hill=PStensor(ellipinf[0],ellipinf[1],ellipinf[2],alpha,0,vol_ellip)
print(PS)
print("Tolerance=",tol,"Error in PS",np.linalg.norm(PS-LamPS)/np.linalg.norm(LamPS))

[-1.16667322e-06 -1.57298492e-06 -3.07364976e-06]
[[-1.16667322e-06  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.57298492e-06  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.07364976e-06]]
elliptic volume, 1.0999780141245126
[[0.057167   0.         0.        ]
 [0.         0.30070657 0.        ]
 [0.         0.         0.64212643]]
Hill Tensor
[[0.057167   0.         0.        ]
 [0.         0.30070657 0.        ]
 [0.         0.         0.64212643]]
solution to min problem [-0.14542219  0.30058257]
solution to min problem [0.14542218 0.30058259]
Ellipsoid found is  [1.81788739 0.54642531 0.26436114]
0.05716699522798525
PS Tensor
[[-1.16667322e-06 -0.00000000e+00 -0.00000000e+00]
 [-0.00000000e+00 -1.57298489e-06 -0.00000000e+00]
 [-0.00000000e+00 -0.00000000e+00 -3.07364987e-06]]
Hill Tensor
[[0.057167   0.         0.        ]
 [0.         0.30070656 0.        ]
 [0.         0.         0.64212644]]
[[-1.16667322e-06 -0.00000000e+00 -0.00000000e+00]
 [-0.00000000e+00 -1.